server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://msa-mariadb.c1may2aymlys.ap-northeast-2.rds.amazonaws.com:3306/UsersService 
    username: MSA_User
    password: password123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true






